name: Sonar

on:
  push:
    branches:
      - main

jobs:
  go-test:
    name: Go test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Make - Run go test
        run: make test

  sonar:
    name: Sonar scan
    runs-on: ubuntu-latest
    needs: go-test

    steps:
      - uses: actions/checkout@v3
      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
